{{- if .Values.caddy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulse.fullname" . }}-caddy
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: caddy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: caddy
    spec:
      containers:
        - name: caddy
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag }}"
          ports:
            - name: https
              containerPort: 443
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddyfile
          configMap:
            name: {{ include "pulse.fullname" . }}-caddy
{{- end }}

