apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulse.fullname" . }}-config
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
data:
  NATS_URL: "nats://{{ .Release.Name }}-nats:4222"

