apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulse.fullname" . }}-keycloak
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: http

