apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulse.fullname" . }}-provision-api
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: provision-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: provision-api
  ports:
    - name: http
      port: 8081
      targetPort: http

