{{- if .Values.routeDelivery.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pulse.fullname" . }}-route-delivery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pulse.fullname" . }}-route-delivery
  minReplicas: {{ .Values.routeDelivery.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.routeDelivery.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.routeDelivery.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

