apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulse.fullname" . }}-ui
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: 80
      targetPort: http

