global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: "ui_iot"
    static_configs:
      - targets: ["ui:8080"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "ingest_iot"
    static_configs:
      - targets: ["ingest:8080"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "evaluator_iot"
    static_configs:
      - targets: ["evaluator:8080"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "ops_worker"
    static_configs:
      - targets: ["ops_worker:8080"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
